### ISSUE TITLE
Add Pixiv's Fanbox

### ISSUE THREAD

**Issue by Qwaxi-Lixard** [Qwaxi-Lixard/yes-porn-allowed#1]
Suggestion from:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Great idea! Thanks for putting this together!<br><br>One subscription site I would recommend is <a href="https://t.co/LK7kZiIsSP">https://t.co/LK7kZiIsSP</a> (part of Pixiv). They&#39;re far more tolerant of adult works than Patreon, though require Japanese-style censorship of exposed sexual organs.<a href="https://t.co/dFDyH3BDoT">https://t.co/dFDyH3BDoT</a></p>&mdash; LigLig 🍂 (@composingliger) <a href="https://twitter.com/composingliger/status/1459331976456916997?ref_src=twsrc%5Etfw">November 13, 2021</a></blockquote>

**Comment by composingliger** [comment]
Service: [pixivFANBOX](https://www.fanbox.cc/)

Here are the relevant policies and guidelines I'm aware of.

From [pixiv Inc. Service Master Terms of Use](https://policies.pixiv.net/en.html):

> ## Master Terms of Use
> ### Article 14. Prohibited Conduct
> When using the Services, User must not engage in the conduct set forth in the following items.
>
> 26. Using the Services to display, sell, purchase, register, or engage in other transactions involving the products set forth below:
>
>       5. Products that contain uncorrected representations of exposed sexual organs or explicit images of sexual intercourse;

> ## pixivFANBOX
> ### Article 7. Posting
> Creators may not publish posts that fall under any of the following. If the Company determines that a post falls under any one of the following, the Company is entitled to request that the registered Creator revise the post or make the post private in whole or in part, and depending on the circumstances, the Company may cancel the Creator registration of the relevant Creator.
> 1. Obscene or excessively deviant sexual expression;
> ...

From [Pixiv Guidelines](https://www.pixiv.net/terms/?page=guideline&lang=en):

> ## About censorship (mosaics/pixelation)
> - Generally speaking, the censorship process assumes that any inappropriate parts shall be hidden based on visual judgment rather than on the technical nature of the image.
> - Censorship shall be efficiently done until it has achieved a level where no programs can reverse the edit.
> - The range should include the outline.
> - Vague mosaics/pixelation where details are made clear by the transparency of the concealment shall not be considered as censorship.
> - The following are guidelines for using mosaics/pixelation:
>     - Mosaics should use squares at least 4x4 pixels in size. If the said image is more than 400 pixels long, the dimensions of the mosaic squares should be 1/100 the length of the whole image.
> - Censorship using solid colors should conceal all inappropriate parts of the image. However, exceptions can be made if concealing only a part of the image leads to an acceptable result.
> - Censorship using white liquids and other patterns or painting techniques which goal is censorship should conceal all inappropriate parts of the image. However, exceptions can be made if concealing only a part of the image leads to an acceptable result.
> ## Examples of expressions that require the use of mosaics/pixelation
> - Genitals or areas reminiscent of genitals
> - The union or joining of the genitals and the insertion of foreign objects
> - The union or joining of anuses and the insertion of foreign objects
> - Areas that are unnecessarily detailed due to being exposed by cuts, lacerations, etc.

**Comment by Qwaxi-Lixard** [comment]
Thank you for the extra information!

**Comment by Qwaxi-Lixard** [comment]
Added to list in dab1a5c2b622db3289501dde61a71912165e469f
