### ISSUE TITLE
Add nearlyfreespeech.net  to Yes Porn Allow list

### ISSUE THREAD

**Issue by dalmationer** [Qwaxi-Lixard/yes-porn-allowed#12]
**What is the site you want to add?**
nearlyfreespeech.net 

**What kind of service are they?**

Web hosting.

**How does the site tend to treat NSFW content?**

Explicitly allowed

**Do you know of any risk to the site?**

Nope.

**Any comment you want to add about the site?**

Nearlyfreespeech have a big emphasis on free speech.. It's in the name lol. They will host anything, as long as it's legal, but unfortunately this DOES include fascists etc. They try to make up for this by spending all the money they make from such projects on organisations which oppose the goals of them. You can read up on this in their FAQ: search for "MFFAM"

**Comment by Qwaxi-Lixard** [comment]
I've added your additions (including notes) to the list, thank you very much.
