### ISSUE TITLE
Add "Element" to Yes Porn Allow list

### ISSUE THREAD

**Issue by E1int** [Qwaxi-Lixard/yes-porn-allowed#17]
**What is the site you want to add?**
[Element](https://element.io/)

**What kind of service are they?**
Communication Services

**How does the site tend to treat NSFW content?**
Their [TOS](https://element.io/terms-of-service) doesn't mention anything regarding pornographic content.

**Do you know of any risk to the site?**
None that I can think of other than a change to the TOS.

**Any comment you want to add about the site?**
The [homeserver](https://github.com/matrix-org/synapse) is open source and self-hostable.

**Comment by Qwaxi-Lixard** [comment]
Added Element (and Matrix) in 26ef74d3113ab371af5c8c9901d7ae0fd9d4737f
