### ISSUE TITLE
Add "dreamwidth.org" to Yes Porn Allow list

### ISSUE THREAD

**Issue by momijizukamori** [Qwaxi-Lixard/yes-porn-allowed#27]
**What is the site you want to add?**
[Dreamwidth](dreamwidth.org)

**What kind of service are they?**
Social Media

**How does the site tend to treat NSFW content?**
Allowed if it's legal under US law ([ToS section XI](https://www.dreamwidth.org/legal/tos)). [Marking enouraged but not mandatory](https://www.dreamwidth.org/support/faqbrowse?faqid=147).

**Do you know of any risk to the site?**
No 

**Any comment you want to add about the site?**
'Slow' social media (this may be a pro or a con). Image hosting limited to on-site display only. Strong privacy features. Site is fully user-funded, and [site owners have a strong commitment to protecting first amendment rights](https://dw-news.dreamwidth.org/43389.html)

**Comment by rahaeli** [comment]
Site owner here to confirm: as long as it's not child sex abuse material (CSAM) by US law, we allow all pornographic content, whether visual or written, and we have in fact turned up in court to help protect users' rights. We have very limited on-site photo hosting and don't allow hotlinking, so we're not a good fit for anyone who's looking for image or video hosting, but we have a large contingent of erotica writers, erotic roleplayers, and adult-content bloggers.

**Comment by Qwaxi-Lixard** [comment]
Finally got around to adding this to the list. Definitely a good addition!
