### ISSUE TITLE
Remove gotm.io

### ISSUE THREAD

**Issue by holasoiflair** [Qwaxi-Lixard/yes-porn-allowed#32]
> Gotm.io is a Godot Engine focused hosting service that allows pornographic games. However, they can only be privately accessed by direct link

[About that](https://gotm.io)
![image](https://github.com/Qwaxi-Lixard/yes-porn-allowed/assets/128470986/fa9305e6-8590-4f03-9774-b5b134c33b6c)

**Comment by Qwaxi-Lixard** [comment]
That's an oof of a different flavor. Thanks for the update
