### ISSUE TITLE
Add Shopify to Yes Porn Allow list?

### ISSUE THREAD

**Issue by holasoiflair** [Qwaxi-Lixard/yes-porn-allowed#33]
**What is the site you want to add?**
[Shopify](https://www.shopify.com/)

**What kind of service are they?**
Merchant Service/E-Commerce

**How does the site tend to treat NSFW content?**
I have yet to see a concrete example of a site with Shopify selling adult content but
[a reply to a forum question by official staff](https://community.shopify.com/c/shopify-design/opening-an-adult-store/m-p/1701168/highlight/true#M454953) and an [official blog post about selling sex toys](https://www.shopify.com/blog/sell-sex-toys) does seem to suggest that you are allowed to sell adult content.
Further more, neither their [acceptable use policy](https://www.shopify.com/legal/aup) nor their [Terms of Service](https://www.shopify.com/legal/terms) seems to have any clause about obscene or pornographic content.

**Do you know of any risk to the site?**
Site is dependent on payment processors like Stripe and PayPal.
Further more, they could also change their policy, since a [more recent answer](https://community.shopify.com/c/shopify-discussions/is-adult-content-allowed-with-a-shopify-store/m-p/2154015/highlight/true#M373203) is more vague about selling porn or not. They might have had a obscenity clause in the past but besides [this quora answer](https://www.quora.com/Can-you-sell-adult-items-on-Shopify) I didn't find anything confirming that.

**Any comment you want to add about the site?**
Given Gumroad's downfall this might be a possible replacement?

**Comment by Qwaxi-Lixard** [comment]
I imagine "porn" is too big of an umbrella for a cut and dry answer. Generally selling nudes is where places can start to have trouble with the US's human trafficking laws. You'd probably need some way to convince shopify you are all above board or whatever.
