### ISSUE TITLE
Add "Newgrounds" to Yes Porn Allow list

### ISSUE THREAD

**Issue by Hyratel** [Qwaxi-Lixard/yes-porn-allowed#37]
**What is the site you want to add?**
Newgrounds: Newgrounds.com

**What kind of service are they?**
Art Gallery / Game Hosting (probably fits under Game Hosting best, for this list)

**How does the site tend to treat NSFW content?**
Allowed, if marked

**Do you know of any risk to the site?**
None

**Any comment you want to add about the site?**
Multimedia Gallery Site, Allows static art, movie format, and games. One of the oldest continuously-operating Gallery Sites, fully independent.

**Comment by Qwaxi-Lixard** [comment]
Added to the list
