### ISSUE TITLE
Remove https://autonomic.zone/ from the list.

### ISSUE THREAD

**Issue by ZanaGB** [Qwaxi-Lixard/yes-porn-allowed#43]
I have sent some correspondence to them a while back, and, paraphrasing the email i have just gotten from them, to remove specifics, thry "spent the last two weeks deliberating what should be done, as they  use servers on Digital Ocean and Hetzner, which (by their own admission) are ill-suited for the task." They also "have no idea how they ended up in that list since they have never worked hosting adult content"

It may be a good idea to remove them off the list. For they are ill suited for hosting this sort of content.

**Comment by Qwaxi-Lixard** [comment]
I work off the legal agreement information I can find (as well as the legal agreements between any 3rd party services they note in said legal agreements). But given this, I'll prune them from the list.

**Comment by ZanaGB** [comment]
The website itself doesn't mention that they would have grounds to oppose, and from the email exchange i don't think they would either, if they did not rely on Hetzner. So it's probably best to err in the side of caution indeed.
